version: '3.8'

services:
  app:
    build: .
    container_name: hono-app
    env_file:
      - .env
    networks:
      - traefik
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hono.rule=Host(`app.shollu.com`)"
      - "traefik.http.routers.hono.entrypoints=websecure"
      - "traefik.http.routers.hono.tls.certresolver=letsencrypt"
      - "traefik.http.services.hono.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
  web:
    external: true
