version: '3.8'

services:
  app:
    build: .
    container_name: hono-app
    env_file:
      - .env
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.waha.rule=Host(`app.shollu.com`)"
      - "traefik.http.routers.waha.entrypoints=websecure"
      - "traefik.http.routers.waha.tls.certresolver=myresolver"
      - "traefik.http.services.waha.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true

volumes:
  db_data:
